# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_calc_new.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(315, 435)
        Calculator.setStyleSheet("background-color: #d3d3d3;")
        self.label_main = QtWidgets.QLabel(Calculator)
        self.label_main.setGeometry(QtCore.QRect(10, 30, 295, 55))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_main.setFont(font)
        self.label_main.setStyleSheet("background-color: #8fbc8b;\n"
"border: 1px inset grey;\n"
"qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
"")
        self.label_main.setObjectName("label_main")
        self.pushButton_7 = QtWidgets.QPushButton(Calculator)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 210, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Calculator)
        self.pushButton_8.setGeometry(QtCore.QRect(85, 210, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Calculator)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 210, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_multiply = QtWidgets.QPushButton(Calculator)
        self.pushButton_multiply.setGeometry(QtCore.QRect(235, 265, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("background-color: rgb(185, 185, 185)")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_4 = QtWidgets.QPushButton(Calculator)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 265, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Calculator)
        self.pushButton_5.setGeometry(QtCore.QRect(85, 265, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Calculator)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 265, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_substract = QtWidgets.QPushButton(Calculator)
        self.pushButton_substract.setGeometry(QtCore.QRect(235, 320, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_substract.setFont(font)
        self.pushButton_substract.setStyleSheet("background-color: rgb(185, 185, 185)")
        self.pushButton_substract.setObjectName("pushButton_substract")
        self.pushButton_divide = QtWidgets.QPushButton(Calculator)
        self.pushButton_divide.setGeometry(QtCore.QRect(235, 210, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setStyleSheet("background-color: rgb(185, 185, 185)")
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_add = QtWidgets.QPushButton(Calculator)
        self.pushButton_add.setGeometry(QtCore.QRect(235, 375, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("background-color: rgb(185, 185, 185)")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_equal = QtWidgets.QPushButton(Calculator)
        self.pushButton_equal.setGeometry(QtCore.QRect(160, 95, 145, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setStyleSheet("background-color: rgb(185, 185, 185)")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_3 = QtWidgets.QPushButton(Calculator)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 320, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_1 = QtWidgets.QPushButton(Calculator)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 320, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Calculator)
        self.pushButton_2.setGeometry(QtCore.QRect(85, 320, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_plus_minus = QtWidgets.QPushButton(Calculator)
        self.pushButton_plus_minus.setGeometry(QtCore.QRect(10, 375, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus_minus.setFont(font)
        self.pushButton_plus_minus.setStyleSheet("background-color: rgb(185, 185, 185)")
        self.pushButton_plus_minus.setObjectName("pushButton_plus_minus")
        self.pushButton_0 = QtWidgets.QPushButton(Calculator)
        self.pushButton_0.setGeometry(QtCore.QRect(85, 375, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_point = QtWidgets.QPushButton(Calculator)
        self.pushButton_point.setGeometry(QtCore.QRect(160, 375, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_point.setFont(font)
        self.pushButton_point.setStyleSheet("background-color: rgb(185, 185, 185)")
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_clear = QtWidgets.QPushButton(Calculator)
        self.pushButton_clear.setGeometry(QtCore.QRect(10, 95, 70, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setMouseTracking(False)
        self.pushButton_clear.setAutoFillBackground(False)
        self.pushButton_clear.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #B22222;")
        self.pushButton_clear.setAutoRepeat(False)
        self.pushButton_clear.setAutoExclusive(False)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_save = QtWidgets.QPushButton(Calculator)
        self.pushButton_save.setGeometry(QtCore.QRect(235, 155, 70, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("color: #363663;\n"
"background-color: rgb(150, 150, 150)")
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_factorial = QtWidgets.QPushButton(Calculator)
        self.pushButton_factorial.setGeometry(QtCore.QRect(10, 155, 70, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_factorial.setFont(font)
        self.pushButton_factorial.setStyleSheet("background-color: rgb(150, 150, 150)")
        self.pushButton_factorial.setObjectName("pushButton_factorial")
        self.pushButton_power = QtWidgets.QPushButton(Calculator)
        self.pushButton_power.setGeometry(QtCore.QRect(85, 155, 70, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_power.setFont(font)
        self.pushButton_power.setStyleSheet("background-color: rgb(150, 150, 150)")
        self.pushButton_power.setObjectName("pushButton_power")
        self.pushButton_root = QtWidgets.QPushButton(Calculator)
        self.pushButton_root.setGeometry(QtCore.QRect(160, 155, 70, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_root.setFont(font)
        self.pushButton_root.setStyleSheet("background-color: rgb(150, 150, 150)")
        self.pushButton_root.setObjectName("pushButton_root")
        self.label_upper = QtWidgets.QLabel(Calculator)
        self.label_upper.setGeometry(QtCore.QRect(10, 5, 295, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.label_upper.setFont(font)
        self.label_upper.setStyleSheet("qproperty-alignment: \'AlignVCenter | AlignRight\';")
        self.label_upper.setObjectName("label_upper")
        self.pushButton_backspace = QtWidgets.QPushButton(Calculator)
        self.pushButton_backspace.setGeometry(QtCore.QRect(85, 95, 70, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_backspace.setFont(font)
        self.pushButton_backspace.setMouseTracking(False)
        self.pushButton_backspace.setAutoFillBackground(False)
        self.pushButton_backspace.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #708090;")
        self.pushButton_backspace.setAutoRepeat(False)
        self.pushButton_backspace.setAutoExclusive(False)
        self.pushButton_backspace.setObjectName("pushButton_backspace")

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Form"))
        self.label_main.setText(_translate("Calculator", "0"))
        self.pushButton_7.setText(_translate("Calculator", "7"))
        self.pushButton_8.setText(_translate("Calculator", "8"))
        self.pushButton_9.setText(_translate("Calculator", "9"))
        self.pushButton_multiply.setText(_translate("Calculator", "×"))
        self.pushButton_4.setText(_translate("Calculator", "4"))
        self.pushButton_5.setText(_translate("Calculator", "5"))
        self.pushButton_6.setText(_translate("Calculator", "6"))
        self.pushButton_substract.setText(_translate("Calculator", "−"))
        self.pushButton_divide.setText(_translate("Calculator", "÷"))
        self.pushButton_add.setText(_translate("Calculator", "+"))
        self.pushButton_equal.setText(_translate("Calculator", "="))
        self.pushButton_3.setText(_translate("Calculator", "3"))
        self.pushButton_1.setText(_translate("Calculator", "1"))
        self.pushButton_2.setText(_translate("Calculator", "2"))
        self.pushButton_plus_minus.setText(_translate("Calculator", "±"))
        self.pushButton_0.setText(_translate("Calculator", "0"))
        self.pushButton_point.setText(_translate("Calculator", "."))
        self.pushButton_clear.setText(_translate("Calculator", "C"))
        self.pushButton_save.setText(_translate("Calculator", "🖬"))
        self.pushButton_factorial.setText(_translate("Calculator", "n!"))
        self.pushButton_power.setText(_translate("Calculator", "xʸ"))
        self.pushButton_root.setText(_translate("Calculator", "ⁿ√x"))
        self.label_upper.setText(_translate("Calculator", ""))
        self.pushButton_backspace.setText(_translate("Calculator", "🠔"))
